// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package easyjson2struct

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson1aeb6805DecodeGoProgramEasyjson2struct(in *jlexer.Lexer, out *People) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Name":
			out.Name = string(in.String())
		case "Sex":
			out.Sex = int(in.Int())
		case "Phone":
			out.Phone = string(in.String())
		case "ID":
			out.ID = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1aeb6805EncodeGoProgramEasyjson2struct(out *jwriter.Writer, in People) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"Sex\":"
		out.RawString(prefix)
		out.Int(int(in.Sex))
	}
	{
		const prefix string = ",\"Phone\":"
		out.RawString(prefix)
		out.String(string(in.Phone))
	}
	{
		const prefix string = ",\"ID\":"
		out.RawString(prefix)
		out.Int(int(in.ID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v People) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1aeb6805EncodeGoProgramEasyjson2struct(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v People) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1aeb6805EncodeGoProgramEasyjson2struct(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *People) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1aeb6805DecodeGoProgramEasyjson2struct(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *People) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1aeb6805DecodeGoProgramEasyjson2struct(l, v)
}
